<div id="admin_content_statistics">
    <h3>Сатистика</h3>
    <form name="date_interval" action="<?=$this->action?>" method="get">
        <table class="admin_date_interval">
            <tr>
                <td colspan="2">
                    <span>За период:</span>
                </td>
            </tr>
            <tr>
                <td>с:</td>
                <td>
                    <input type="date" name="date_from" value="<?=$this->date_from?>">
                </td>
                <td>по:</td>
                <td>
                    <input type="date" name="date_to" value="<?=$this->date_to?>">
                </td>
                <td colspan="2">
                    <input type="hidden" name="func" value="show_statistics">
                    <input type="submit" name="show_statistics" value="Показать">
                </td>
            </tr>
        </table>
    </form>
    <?php if($this->orders_statistics) : ?>
    <table class="admin_stats_table">
        <tr>
            <td>Количество заказов</td>
            <td>Счетов на сумму</td>
            <td>Доход</td>
            <td>Купленных DVD</td>
        </tr>
        <tr>
            <td><?=$this->orders_statistics['count_orders']?></td>
            <td><?=$this->orders_statistics['summ_accounts']?> рублей</td>
            <td><?=$this->orders_statistics['income']?> рублей</td>
            <td><?=$this->orders_statistics['count_dvd']?></td>
        </tr>
    </table>
    <?php endif; ?>
</div>