<div id="admin_table_form">
    <h3><?=$this->form_title?></h3>
    <?php include 'message.phtml'; ?>
    <div class="form">
        <form name="section" action="<?=$this->action?>" method="post">
            <table>
                <tr>
                    <td>Название:</td>
                    <td>
                        <input type="text" name="section_title" value="<?=$this->section_title?>">
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <input type="hidden" name="id" value="<?=$this->id?>">
                        <input type="hidden" name="func" value="<?=$this->func?>">
                        <input type="submit" value="Отправить">
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>