<div id="admin_table_info">
    <h3>Купоны</h3>
    <?php include 'message.phtml'; ?>
    <p class="link_add">
        <a href="<?=$this->link_add?>">Добавить новый купон</a>
    </p>
    <table class="info">
        <tr class="header">
            <td>ID</td>
            <td>Код купона</td>
            <td>Скидка</td>
            <td>Функции</td>
        </tr>
        <?php foreach ($this->table_data as $tableData) { ?>
            <tr>
                <td><?=$tableData['id']?></td>
                <td>
                    <?=$tableData['code']?>
                </td>
                <td>
                    <?=($tableData['value'] * 100) . '%'?>
                </td>
                <td>
                    <a href="<?=$tableData['link_admin_edit']?>">Редактировать</a><br>
                    <a href="<?=$tableData['link_admin_delete']?>" onclick="return confirm('Вы уверены, что хотите удалить элемент?')"> Удалить</a>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>