<div id="admin_table_info">
    <h3>Товары</h3>
    <?php include 'message.phtml'; ?>
    <p class="link_add">
        <a href="<?=$this->link_add?>">Добавить новую секцию</a>
    </p>
    <table class="info">
        <tr class="header">
            <td>ID</td>
            <td>Название</td>
            <td>Функции</td>
        </tr>
        <?php foreach ($this->table_data as $tableData) { ?>
            <tr>
                <td><?=$tableData['id']?></td>
                <td>
                    <a href="<?=$tableData['link']?>"><?=$tableData['title']?></a>
                    <br>
                    <?=$this->section_title?>
                </td>
                <td>
                    <a href="<?=$tableData['link_admin_edit']?>">Редактировать</a><br>
                    <a href="<?=$tableData['link_admin_delete']?>" onclick="return confirm('Вы уверены, что хотите удалить элемент?')"> Удалить</a>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>