<div id="admin_table_info">
    <h3>Заказы</h3>
    <?php include 'message.phtml'; ?>
    <p class="link_add">
        <a href="<?=$this->link_add?>">Добавить новый заказ</a>
    </p>
    <table class="info admin_orders">
        <tr class="header">
            <td>ID</td>
            <td>Способ доставки</td>
            <td>Заказ</td>
            <td>Цена</td>
            <td>ФИО</td>
            <td>Телефон</td>
            <td>E-mail</td>
            <td>Адрес</td>
            <td>Примечание</td>
            <td>Дата заказа</td>
            <td>Дата отправки</td>
            <td>Дата оплаты</td>
            <td>Функции</td>
        </tr>
        <?php foreach ($this->table_data as $tableData) { ?>
            <tr>
                <td><?=$tableData['id']?></td>
                <td>
                    <?=($tableData['delivery'] === 0) ? 'Доставка' : 'Самовывоз'?>
                </td>
                <td>
                    <?php if(isset($tableData['products'])) : ?>
                        <ol>
                        <?php foreach ($tableData['products'] as $product) { ?>
                            <?php foreach ($product as $title => $count) { ?>
                                <li>
                                    <?=$title . ' x ' ?> <b><?=$count?></b>
                                </li>
                            <?php }} ?>
                        </ol>
                        <?php else : ?>
                            <p class="red_message">Товаров не найдено! <br> Возможно они были удалены.</p>
                        <?php endif; ?>
                </td>
                <td><?=$tableData['price']?></td>
                <td><?=$tableData['name']?></td>
                <td><?=$tableData['phone']?></td>
                <td><?=$tableData['email']?></td>
                <td><?=$tableData['address']?></td>
                <td><?=$tableData['notice']?></td>
                <td><?=$tableData['date_order']?></td>
                <td><?=$tableData['date_send']?></td>
                <td><?=$tableData['date_pay']?></td>
                <td>
                    <a href="<?=$tableData['link_admin_edit']?>">Редактировать</a><br>
                    <a href="<?=$tableData['link_admin_delete']?>" onclick="return confirm('Вы уверены, что хотите удалить элемент?')"> Удалить</a>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>