<h3><?=$this->admin_title?></h3>
<?php include 'message.phtml'; ?>
<div id="admin_auth_form">
    <form name="auth" action="<?=$this->action?>" method="post">
        <table>
            <tr>
                <td>Логин: </td>
                <td>
                    <input type="text" name="login" value="<?=$this->login?>">
                </td>
            </tr>
            <tr>
                <td>Пароль: </td>
                <td>
                    <input type="password" name="password">
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="hidden" name="func" value="admin_auth">
                    <input type="submit" name="auth" value="Войти">
                </td>
            </tr>
        </table>
    </form>
</div>