<table>
    <tr>
        <td rowspan="2">
            <div class="header">
                <h3><?=$this->table_products_title?></h3>
            </div>
        </td>
        <td>
            <div id="new_items_header_line"></div>
        </td>
    </tr>
    <tr>
        <td id="sort_new_items_header">
            <table>
                <tr>
                    <td>Сортировать по:</td>
                    <td>цене (<span>возр.</span> | <span>убыв.</span>)</td>
                    <td>названию (<span>возр.</span> | <span>убыв.</span>)</td>
                </tr>
            </table>
        </td>
    </tr>
</table>