<table>
    <tr>
        <td rowspan="2">
            <div class="header">
                <h3><?=$this->table_products_title?></h3>
            </div>
        </td>
        <td>
            <div id="new_items_header_line"></div>
        </td>
    </tr>
    <tr>
        <td id="sort_new_items_header">
            <table>
                <tr>
                    <td>Сортировать по:</td>
                    <td>цене (<a href="<?=$this->link_price_up?>">возр.</a> | <a href="<?=$this->link_price_down?>">убыв.</a>)</td>
                    <td>названию (<a href="<?=$this->link_title_up?>">возр.</a> | <a href="<?=$this->link_title_down?>">убыв.</a>)</td>
                </tr>
            </table>
        </td>
    </tr>
</table>